#!/bin/zsh

function install_gem() {
  [[ ! $(gem list $1 | grep $1) ]] \
    && gem install $1 \
    || info "$1 gem already installed"
}

ruby_version="$(plugin_version ruby)"

asdf plugin add ruby &> /dev/null || info "ruby plugin already added"
asdf install ruby $ruby_version &> /dev/null || info "ruby already installed"

install_gem neovim
install_gem pry
install_gem awesome_print
