tap "homebrew/cask-fonts"

cask "1password"
cask "1password-cli"
cask "alacritty"
cask "firefox"
cask "obsidian"
cask "orbstack"
cask "protonmail-bridge"
cask "raycast"
cask "tidal"
cask "todoist"
cask "telegram"
cask "homebrew/cask-fonts/font-hack-nerd-font"

brew "curl"
brew "direnv"
brew "fzf"
brew "git"
brew "git-open"
brew "gpg"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "wget"
brew "zsh"
