#!/bin/zsh

DOTFILES=$HOME/.dotfiles
cd $DOTFILES

set -e

info () {
  printf "[\033[00;34m..\033[0m] $1\n"
}

user () {
  printf "[\033[0;33m$1\033[0m] $2\n"
}

success () {
  printf "\n\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\n\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
}

system_install() {
  for src in $(find -H "$DOTFILES" -name 'install'); do
    info "Running install for $src"
    source $src
  done
}

install_dotfiles () {
  info 'Symlinking Dotfiles'
  for src in $(find -H "$DOTFILES" -name '*.symlink'); do
    dst="$HOME/.$(basename "${src%.*}")"

    if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]; then
      if [ "$(readlink $dst)" -ef "$src" ]; then
        rm -rf "$dst"
      fi
    fi

    ln -s "$src" "$dst"
    success "linked $src to $dst"
  done
}

update_dotfiles () {
  for src in $(find -H "$DOTFILES" -name '*.symlink'); do
    dst="$HOME/.$(basename "${src%.*}")"

    if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]; then
      if [ "$(readlink $dst)" -ef "$src" ]; then
        continue
      fi
    fi

    ln -s "$src" "$dst"
    success "linked $src to $dst"
  done
}

update_submodules () {
  info 'Updating git submodules'
  $(git submodule update --remote &> /dev/null)
}

install() {
  system_install
  update_submodules
  install_dotfiles
}

update () {
  update_submodules
  info 'Updating Dotfiles'
  update_dotfiles
  success 'Dotfiles installed'
}

run() {
  local action=

  while [[ true ]]; do
    user "i" "Install\tClean install (overides existing symlinks)"
    user "u" "Update\tAdd missing symlinks, update submodules, update applications"
    user "e" "Exit"

    printf " > "
    read action

    if [[ "$action" == "i" ]]; then
      install
    elif [[ "$action" == "u" ]]; then
      update
    elif [[ "$action" == "e" ]]; then
      echo 'Bye!'
      exit
    else
      fail "Invalid command!"
    fi
    echo ''
  done
}
run
