#!/bin/zsh

DOTFILES=$HOME/.dotfiles
if [ ! -d "$DOTFILES" ]; then
  mkidir "$DOTFILES"
fi

cd $DOTFILES

set -e

info () {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
}

install_dotfiles () {
  info 'Installing Dotfiles'
  for src in $(find -H "$DOTFILES" -name '*.symlink'); do
    dst="$HOME/.$(basename "${src%.*}")"

    if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]; then
      if [ "$(readlink $dst)" -ef "$src" ]; then
        rm -rf "$dst"
      fi
    fi

    ln -s "$src" "$dst"
    success "linked $src to $dst"
  done
}

update_dotfiles () {
  for src in $(find -H "$DOTFILES" -name '*.symlink'); do
    dst="$HOME/.$(basename "${src%.*}")"

    if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]; then
      if [ "$(readlink $dst)" -ef "$src" ]; then
        continue
      fi
    fi

    ln -s "$src" "$dst"
    success "linked $src to $dst"
  done
}

update_submodules () {
  info 'Updating git submodules'
  $(git submodule update --remote &> /dev/null)
}

install() {
  update_submodules
  install_dotfiles

  info 'Installing Vim plugins'
  [[ ! -d "$HOME/.vim" ]] && mkdir "$HOME/.vim" && info 'Creating .vim folder'
  $(vim +PluginInstall +qall &> /dev/null)

  success 'Plugins installed'
}

commit () {
  local message=
  local yes=
  info 'Repo changes:'
  echo "$(git status --porcelain | sed -e 's/\(\n|\r\)/\t\1/g')"
  user 'Confirm changes? [y/n]'
  printf "   > "
  read yes
  if [[ "$yes" == "y" ]]; then
    user 'Enter the commit message:'
    printf "   > "
    read message
    $(git add -A)
    success "\n$(git commit -m "$message")"
  fi
}

update () {
  update_submodules
  info 'Updating Dotfiles'
  update_dotfiles
  info 'Updating Vim plugins'
  $(vim +PluginUpdate +qall &> /dev/null)
  success 'Plugins Updated'
}

push () {
  info 'Push Changes'
  $(git push origin master)
  success 'Plugins Updated'
}

run_install () {
  local action=

  while [[ true ]]; do
    echo ''
    user "Dotfiles: What do you want to do?\
      \n\t[i]nstall - clean install (overides existing symlinks)\
      \n\t[u]pdate  - add missing symlinks, update submodules and vim plugins\
      \n\t[c]ommit - commit all changes\
      \n\t[p]ush - push all changes\
      \n\t[e]exit   - exit without doing nothing"
    printf "   > "
    read action

    if [[ "$action" == "i" ]]; then
      install
    elif [[ "$action" == "u" ]]; then
      update
    elif [[ "$action" == "c" ]]; then
      commit
    elif [[ "$action" == "p" ]]; then
      push
    elif [[ "$action" == "e" ]]; then
      echo '  All done!'
      echo ''
      exit
    else
      fail "Invalid command!"
    fi
  done

}
run_install
