#!/bin/zsh

info () {
  printf "[\033[00;34m..\033[0m] $1\n"
}

user () {
  printf "[\033[0;33m$1\033[0m] $2\n"
}

success () {
  printf "\033[2K[\033[00;32mOK\033[0m] $1\n"
}

fail () {
  printf "\033[2K[\033[0;31mKO\033[0m] $1\n"
}
