#!/bin/zsh

init_dir="$HOME/.config/nvim"
if [ ! -d "$init_dir" ]; then
  mkdir -p $init_dir
  ln -s "$HOME/.dotfiles/vim/init.vim" "$init_dir/init.vim" && success "linked init.vim file"
  ln -s "$HOME/.dotfiles/vim/coc-settings.json" "$init_dir/coc-settings.json" && \
    success "linked coc-settings.json"
fi
