#!/bin/zsh

brew_install nvm

node_version="v13.12.0"

[ -s "/usr/local/opt/nvm/nvm.sh" ] && source "/usr/local/opt/nvm/nvm.sh"

if [[ ! $(nvm list | grep "$node_version") ]]; then
  nvm install $node_version
  npm install -g yarn
  yarn global add neovim
fi
