#!/bin/zsh

asdf plugin add nodejs &> /dev/null || info "nodejs plugin already added"
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
asdf install nodejs &> /dev/null || info "yarn already installed"

asdf plugin add yarn  &> /dev/null || info "yarn plugin already added"
asdf install yarn &> /dev/null || info "yarn already installed"

yarn global add neovim
