#!/bin/zsh

python_version="$(plugin_version python)"
asdf plugin add python &> /dev/null || info "python plugin already added"
asdf install python &> /dev/null || info "python already installed"
pip3 install pynvim --user
